cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :cats
  resources :cat_rental_requests
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  
  COLORS = [
    'black',
    'white',
    'orange'
  ]
  validates :birth_date, :color, :name, :sex, :description ,presence: true
  validates :color, :inclusion => {:in => Cat::COLORS}
  
  def age
    ((Time.zone.now - @birth_date.to_time) / 1.year.seconds).floor
  end
  
  
  has_many :rental_requests,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy
end
# Cat.create(birth_date: '2010-10-10', color: 'orange', name: 'Tom', sex: 'F', description: 'This is another cat')

cats99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  STATUS = ['PENDING',"APPROVED","DENIED"]
  validates :status, :inclusion => {:in=>CatRentalRequest::STATUS}
  
  belongs_to :cat,
  foreign_key: :cat_id,
  class_name: :Cat
  
  def overlapping_requests
  
    CatRentalRequest.where.not("start_date > #{self.end_date} AND  end_date < #{self.start_date} ")
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end
  
  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
    
  end
  
  def does_not_overlap_approved_request
    CatRentalRequest.exists?(overlapping_approved_requests)
  end
  
  
  def approve
    
     overlapping_pending_requests.each do |req|
      req.status = 'DENIED'
      # update(req.id)
      req.save
    end
    self.status = 'Approved'
    self.save
    
  end
  
  def deny
    self.status = 'DENIED'
  end
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

def new
  @cat_rental_request = CatRentalRequest.new
  render :new
end
def index
  @cat_request = CatRentalRequest.all
  render :index
end

def create
  @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
  if @cat_rental_request.save
    render json: @cat_rental_request
  else
    render :new
  end
end

private
def cat_rental_request_params
  params.require(:cat_rental_request).permit(:cat_id,:start_date,:end_date,:status)
end
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    
    render :show
  end
  
  def new
    @cat = Cat.new
    
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end
  
  def edit 
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  private
  
  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cat_rental_requests/index.html.erb
<ul>
  <% @cat_request.each do |req| %>
    
  <% end %>
</ul>

cats99/app/views/cat_rental_requests/new.html.erb
<form  action="<%= cat_rental_requests_url %>" method="post">
  <label>
    catid:
    <select name= "cat_rental_request[cat_id]">
      <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"> <%=cat.id %></option>
      <% end %>
    </select>
  </label>
  <br>
  <label>
  start_date:
  <input type="date" name="cat_rental_request[start_date]" value="">
  </label>
  <br>
  <label>
  end_date:
  <input type="date" name="cat_rental_request[end_date]" value="">
  </label>
  <br>
  <input type="submit"  value="Create Request">
</form>

cats99/app/views/cats/_cat.html.erb
<table>
  <th>
    <td>name</td>
    <td>sex</td>
    <td>birth_date</td>
    <td>color</td>
    <td>description</td>
    <td></td>
  </th>
  <tr>
    <td><%= cat.name %></td>
    <td><%= cat.sex %> </td>
    <td><%= cat.birth_date %> </td>
    <td><%= cat.color %> </td>
    <td><%= cat.description %></td>
  </tr>
   
</table>

cats99/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
  <% button_value = "Update cat" %>
<% else %>
  <% action_url = cats_url %>
  <% button_value = "Create cat" %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
    name
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <br>
  <label>
    sex
    <input type="radio" name="cat[sex]" value="M" <%= "checked" if cat.sex == 'M' %>>M
    <input type="radio" name="cat[sex]" value="F"<%= "checked" if cat.sex == 'F' %>>F
  </label>
  <br>
  <label>
    color
    <select name="cat[color]">
      <option disabled <%= cat.color ? "" : "selected"%>>-- Please Select --</option>
      <% Cat::COLORS.each do |color| %>
        <option <%= cat.color == color ? "selected" : ""%> ><%= color %></option>
      <% end %>
    </select>
  </label>
  <br>
  <label>
    description
    <textarea name="cat[description]" rows="8" cols="80" > <%= cat.description %></textarea>
  </label>
  <br>
  <label>
    Birth Date
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>
  <br>
  <input type="submit" value=<%= button_value %>>
</form>

cats99/app/views/cats/edit.html.erb
<%= render 'form',cat: @cat,action: :edit %>

cats99/app/views/cats/index.html.erb
<ul>
  
  <% @cats.each do |cat| %>
  
    <li>name: <%= cat.name %></li>
    <li>birth_date: <%= cat.birth_date %></li>
    <li>color: <%= cat.color %></li>
    <li>sex: <%= cat.sex %></li>
    <li>description: <%= cat.description %></li>
    <li><a href="<%= cat_url(cat) %>">Details</a></li>
    <br>
  <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<%= render 'form',action: :new,cat: @cat %>

cats99/app/views/cats/show.html.erb
<%#= render 'cat', cat: @cat, action: :show %>

<table>
  <tr>
    <td>name</td>
    <td>sex</td>
    <td>birth_date</td>
    <td>color</td>
    <td>description</td>
    
    <td></td>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.sex %> </td>
    <td><%= @cat.birth_date %> </td>
    <td><%= @cat.color %> </td>
    <td><%= @cat.description %></td>
  </tr>
   
</table>
<ul>
  <% Cat.find(@cat.id).rental_requests.order(:start_date).pluck(:start_date,:end_date).each do |req| %>
    <li>start_date:<%= req[0] %> end_date:<%= req[1] %>  </li>
    <!-- <li></li> -->
    <% end %>
</ul>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>